# SETTING THIS TO FALSE WILL DISABLE ALL UPDATE CHECKS FROM ALL
# UPDATERS USING THE MOLECULE API FRAMEWORK.
enabled: true

# NOT ALL PROVIDERS ALLOW DOWNLOADS, BUT IN THE CASE THAT ONE DOES, SHOULD WE ATTEMPT
# TO DOWNLOAD THE UPDATE? SETTING THIS TO FALSE WILL DISABLE DOWNLOADS ENTIRELY
attempt-downloads: true

# WHEN A NEW UPDATE IS DETECTED, SHOULD THE UPDATER SEND A SOUND TO ALL AUDIENCE MEMBERS?
# BY SETTING THIS TO FALSE, YOU WILL DISABLE THIS FEATURE
play-sound: true