blank_issues_enabled: false
contact_links:
  - name: View common issues
    url: https://github.com/OMGitzFROST/MoleculeAPI/issues/4
    about: Check the list of known common issues to see if it solves your problem.
  - name: Check past help requests
    url: https://github.com/OMGitzFROST/MoleculeAPI/discussions/categories/q-a
    about: Visit the Q&A forum to search for previous help requests.
  - name: Check past feature suggestions
    url: https://github.com/OMGitzFROST/MoleculeAPI/issues?q=is%3Aissue+label%3A%22type%3A+feature-request%22
    about: Visit the Feature Suggestions forum to view and discuss existing feature suggestions.
  - name: Create help request
    url: https://github.com/OMGitzFROST/MoleculeAPI/discussions/new?category=q-a
    about: Create a support ticket to get help from developers.
  - name: Get help from the community on Discord
    url: https://discord.gg/38JRNJxAVD
    about: Join the Discord for support!